# ~/.config/hypr/hyprlock/colors.conf
#$text_color = rgba(242, 242, 242, 1.0)
#$entry_background_color = rgba(10, 10, 10, 0.6) # Darker/deeper glass
#$entry_border_color = rgba(255, 255, 255, 0.1)
#$entry_color = rgba(242, 242, 242, 1.0)
#$check_color = rgba(137, 180, 250, 0.8) # Soft blue when checking
#$fail_color = rgba(243, 139, 168, 0.8)  # Soft red on fail
$font_family = Inter
$font_family_clock = Inter


$text_color = rgba(d9e2ffFF)
$entry_background_color = rgba(00194411)
$entry_border_color = rgba(8f909955)
$entry_color = rgba(d9e2ffFF)
#$font_family = Google Sans Flex Medium
#$font_family_clock = Google Sans Flex Medium
$font_material_symbols = Material Symbols Rounded
