##############################
### WINDOWS AND WORKSPACES ###
##############################
# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

#windowrule = opacity 0.9 0.8, ^(org.gnome.Nautilus)$
#windowrule = blur, ^(org.gnome.Nautilus)$
#windowrule = rounding 0, ^(org.gnome.Nautilus)$
